version: "3"
services:
  generate-client:
    container_name: generate-client
    image: node:18-alpine
    working_dir: /usr/client
    volumes:
      - ./client:/usr/client
    command: sh -c "npm create vite@latest . -- --template react-ts && npm i"

  client:
    container_name: client
    image: node:18-alpine
    working_dir: /usr/client
    volumes:
      - ./client:/usr/client
    ports:
      - "5173:5173"
    restart: always
    command: sh -c "npm run start:dev"
